# Server
server.port=8080

# MySQL Database
spring.datasource.url=${mysql://root:SvPbsNwpmnNLEJEeyRVvQhZiPxHiGMlT@mysql.railway.internal:3306/railway}
spring.datasource.username=${root}
spring.datasource.password=${SvPbsNwpmnNLEJEeyRVvQhZiPxHiGMlT}
spring.datasource.driver-class-name=${com.mysql.cj.jdbc.Driver}
SPRING_DATASOURCE_URL=${jdbc:mysql://mysql.railway.internal:3306/railway}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${update}
spring.jpa.show-sql=${true}
spring.jpa.properties.hibernate.dialect=${org.hibernate.dialect.MySQLDialect}

# App name
spring.application.name=${backend}

jwt.secret=${7Xn2pK9mR4vL8wQ1uJ6yT3sA5dF0hG}+bN/cE=
jwt.expiration=${86400000}