server.port=8080

spring.datasource.url=${jdbc:mysql://mysql.railway.internal:3306/railway}
spring.datasource.username=${root}
spring.datasource.password=${SvPbsNwpmnNLEJEeyRVvQhZiPxHiGMlT}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

jwt.secret=${7Xn2pK9mR4vL8wQ1uJ6yT3sA5dF0hG+bN/cE=}
jwt.expiration=${J86400000}